<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.8.0.2 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php,v 1.23.2.2.2.1 2006/03/08 19:06:48 nijel Exp $
 * Date: Tue, 28 Mar 2006 11:08:25 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = '192.168.0.23';
$cfg['Servers'][$i]['port'] = '8033';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = 'elit';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

?>
